services:
  app:
    image: ecotrade-backend:latest
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 --workers 3 --access-logfile - --error-logfile - --no-control-socket --worker-tmp-dir /dev/shm core.wsgi:application"

    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - media_data:/app/media

    networks:
      - ecotrade-net

    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=ecotrade-net"

        - "traefik.http.routers.app.rule=Host(`ecotrade.f3-software.com.br`)"
        - "traefik.http.routers.app.entrypoints=websecure"
        - "traefik.http.routers.app.tls=true"
        - "traefik.http.routers.app.tls.certresolver=letsencryptresolver"

        - "traefik.http.services.app.loadbalancer.server.port=8000"

networks:
  ecotrade-net:
    external: true

volumes:
  media_data:
