# Generated by Django 6.0.3 on 2026-03-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lote_scheduling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='residuos/'),
        ),
    ]
